<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HabitTemplateSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('habit_templates')->truncate();

        $now = Carbon::now();

        $templates = [
            // ─── PHYSICAL HEALTH ───
            ['name' => 'Daily Nature Walk', 'category' => 'Physical Health', 'icon' => '🚶', 'description' => 'Take a short, unplugged walk outdoors to lower stress, promote subconscious problem-solving, and transition into a restful state.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 1],
            ['name' => 'Two-Minute Movement Breaks', 'category' => 'Physical Health', 'icon' => '⏱️', 'description' => 'Take a short two-minute walk every hour to overcome the negative effects of prolonged sitting.', 'goal' => 21, 'goal_unit' => 'days', 'repeat_count' => 8, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 2],
            ['name' => 'Mindful Eating', 'category' => 'Physical Health', 'icon' => '🍽️', 'description' => 'Eat slowly, chew your food thoroughly, and focus entirely on the taste and texture of your meal.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 3, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 3],
            ['name' => 'Post-Workout Protein', 'category' => 'Physical Health', 'icon' => '💪', 'description' => 'Consume 20 to 30 grams of protein prior to sleep to increase overnight protein synthesis and muscle repair.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 4],
            ['name' => 'Gym Clothes Priming', 'category' => 'Physical Health', 'icon' => '👟', 'description' => 'Set out your workout clothes, shoes, and water bottle ahead of time to make morning exercise frictionless.', 'goal' => 21, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 3, 'sort_order' => 5],
            ['name' => 'Visual Water Cues', 'category' => 'Physical Health', 'icon' => '💧', 'description' => 'Place a brightly colored water bottle on your nightstand to prompt hydration the moment you wake up.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 6],
            ['name' => 'Sparkling Water Substitution', 'category' => 'Physical Health', 'icon' => '🥤', 'description' => 'Replace daily alcohol or beer consumption with flavored sparkling water or seltzer to step-down a bad habit.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 7],
            ['name' => 'Temptation Bundling Exercise', 'category' => 'Physical Health', 'icon' => '🎧', 'description' => 'Only allow yourself to listen to your favorite podcast or audiobook while you are actively working out.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 8],
            ['name' => 'Taking the Stairs', 'category' => 'Physical Health', 'icon' => '🪜', 'description' => 'Commit to an if/then environmental rule: if you see stairs, take them instead of the elevator.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 3, 'sort_order' => 9],
            ['name' => 'Vegetables First', 'category' => 'Physical Health', 'icon' => '🥦', 'description' => 'Always serve yourself vegetables first when preparing a plate of food to ensure healthy eating.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 2, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 10],
            ['name' => 'Short High-Intensity Training', 'category' => 'Physical Health', 'icon' => '🏋️', 'description' => 'Train at 100 percent effort for shorter durations rather than 70 percent effort for longer, unfocused periods.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 11],
            ['name' => '10-Minute Micro-Workouts', 'category' => 'Physical Health', 'icon' => '🤸', 'description' => 'Commit to doing just ten push-ups or squats on days you lack time, rather than putting up a zero.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 12],
            ['name' => 'Pre-paying for Fitness', 'category' => 'Physical Health', 'icon' => '🏊', 'description' => 'Schedule and pay for a fitness or yoga class ahead of time to lock in your future workout behavior.', 'goal' => 8, 'goal_unit' => 'weeks', 'repeat_count' => 2, 'deadline_value' => 2, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 13],
            ['name' => 'Substitute Craving with Exercise', 'category' => 'Physical Health', 'icon' => '🔄', 'description' => 'Do some weight repetitions every time you feel the urge to smoke or engage in a bad habit.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 14],
            ['name' => 'Tracking Workout Sets', 'category' => 'Physical Health', 'icon' => '📊', 'description' => 'Record each set in a workout journal immediately after finishing it to visually track your progress.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 15],

            // ─── MENTAL HEALTH ───
            ['name' => 'Five-Minute Meditation', 'category' => 'Mental Health', 'icon' => '🧘', 'description' => 'Meditate for just a few minutes a day to physically increase the neural connections required for self-control.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 1],
            ['name' => 'Slow Breathing', 'category' => 'Mental Health', 'icon' => '🌬️', 'description' => 'Breathe in for a count of four and out for a count of six to trigger parasympathetic physiological relaxation.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 2, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 2],
            ['name' => 'Notice Five Things', 'category' => 'Mental Health', 'icon' => '👁️', 'description' => 'Pause and actively notice five things you can see, hear, and physically feel to ground yourself in the present.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 2, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 3],
            ['name' => 'Mindful Tooth Brushing', 'category' => 'Mental Health', 'icon' => '🪥', 'description' => 'Focus entirely on the sounds, smells, and physical sensations of brushing your teeth instead of letting your mind wander.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 2, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 3, 'sort_order' => 4],
            ['name' => 'Mindful Showering', 'category' => 'Mental Health', 'icon' => '🚿', 'description' => 'Pay full attention to the temperature of the water and the smell of soap during your daily shower.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 3, 'sort_order' => 5],
            ['name' => '10 Deep Morning Breaths', 'category' => 'Mental Health', 'icon' => '🌅', 'description' => 'Take ten deep breaths before getting out of bed, focusing on lung movement and gratitude for being alive.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 6],
            ['name' => 'Willingness Diary Tracking', 'category' => 'Mental Health', 'icon' => '📓', 'description' => 'Rate your daily struggle, emotional upset, and behavioral workability on a scale of 0-10 at the end of the day.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 7],
            ['name' => 'Urge Surfing', 'category' => 'Mental Health', 'icon' => '🏄', 'description' => 'Observe your urges as a scientist, breathe into them, and allow them to rise and fall without acting on them.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 8],
            ['name' => 'Values Writing', 'category' => 'Mental Health', 'icon' => '✍️', 'description' => 'Write down exactly what sort of person you want to be across different life domains (family, health, work).', 'goal' => 12, 'goal_unit' => 'months', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 1, 'sort_order' => 9],
            ['name' => 'Observing Self Check-in', 'category' => 'Mental Health', 'icon' => '🪞', 'description' => 'Pause for 20 seconds to notice your thoughts and acknowledge the transcendent part of you that is observing them.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 10],
            ['name' => 'Naming the Story', 'category' => 'Mental Health', 'icon' => '💭', 'description' => 'Silently label negative thoughts to defuse their emotional power.', 'goal' => 21, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 11],

            // ─── PRODUCTIVITY ───
            ['name' => '10-Minute Distraction Delay', 'category' => 'Productivity', 'icon' => '⏸️', 'description' => 'Tell yourself you can give in to a distraction, but you must wait ten minutes first to let the urge pass.', 'goal' => 21, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 1],
            ['name' => 'Timeboxing Your Day', 'category' => 'Productivity', 'icon' => '📅', 'description' => 'Eliminate white space on your calendar by scheduling exactly what you will do and when you will do it.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 2],
            ['name' => 'Weekly Schedule Reflection', 'category' => 'Productivity', 'icon' => '🔍', 'description' => 'Spend 15 minutes weekly reviewing when you followed your schedule and refining it for the next week.', 'goal' => 12, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 3, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 3],
            ['name' => 'Batch Processing Emails', 'category' => 'Productivity', 'icon' => '📧', 'description' => 'Process and reply to emails only during a specifically scheduled timebox on your calendar.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 2, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 4],
            ['name' => '60-90 Minute Work Sprints', 'category' => 'Productivity', 'icon' => '🏃', 'description' => 'Work with intense, unbroken focus for 60 to 90 minutes, followed by a mandatory short break.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 3, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 5],
            ['name' => 'Single-Tasking', 'category' => 'Productivity', 'icon' => '🎯', 'description' => 'Commit to doing only one thing at a time to prevent cognitive degradation and attention residue.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 6],
            ['name' => 'Eat the Frog', 'category' => 'Productivity', 'icon' => '🐸', 'description' => 'Tackle your biggest, hardest, and most important task first thing in the day.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 7],
            ['name' => '5 Second Rule', 'category' => 'Productivity', 'icon' => '5️⃣', 'description' => 'Count backward from 5 to 1 and physically move before your brain can hesitate and procrastinate.', 'goal' => 21, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 8],
            ['name' => 'Capturing Open Loops', 'category' => 'Productivity', 'icon' => '📝', 'description' => 'Immediately write down any task or idea into a trusted external system to clear your mind.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 9],
            ['name' => 'Weekly Review (GTD)', 'category' => 'Productivity', 'icon' => '🔄', 'description' => 'Dedicate one hour weekly to empty your inbox, review your goals, and plan the upcoming week.', 'goal' => 12, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 3, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 10],
            ['name' => 'Miracle Morning Routine', 'category' => 'Productivity', 'icon' => '🌄', 'description' => 'Start the day with a sequence of silence, affirmations, visualization, exercise, reading, and planning.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 11],
            ['name' => 'Noting Internal Triggers', 'category' => 'Productivity', 'icon' => '📌', 'description' => 'Write down the time, task, and emotion you felt immediately before feeling the urge to get distracted.', 'goal' => 21, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 12],
            ['name' => 'Tagging Emails by Urgency', 'category' => 'Productivity', 'icon' => '🏷️', 'description' => 'Label emails based on whether they need a reply "Today" or "This Week" instead of reacting instantly.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 13],

            // ─── DISCIPLINE ───
            ['name' => 'Habit Stacking', 'category' => 'Discipline', 'icon' => '🔗', 'description' => 'Anchor a new habit to an existing one using the formula: "After Current Habit, I will New Habit".', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 1],
            ['name' => 'Implementation Intentions', 'category' => 'Discipline', 'icon' => '📋', 'description' => 'Use the formula: "I will Behavior at Time in Location" to plan your actions precisely.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 2],
            ['name' => 'Habits Scorecard', 'category' => 'Discipline', 'icon' => '📊', 'description' => 'Make a list of your daily habits and mark them as positive, negative, or neutral to build behavioral awareness.', 'goal' => 12, 'goal_unit' => 'months', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 2, 'sort_order' => 3],
            ['name' => 'Goldilocks Rule', 'category' => 'Discipline', 'icon' => '🐻', 'description' => 'Work on tasks that are just on the edge of your current abilities to maintain maximum motivation and flow.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 4],
            ['name' => 'Identity-Based Phrasing', 'category' => 'Discipline', 'icon' => '🪪', 'description' => 'Say "I am a noun" instead of "I want to be" to align your actions with your desired self-image.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 5],
            ['name' => '1% Daily Improvement Tracking', 'category' => 'Discipline', 'icon' => '📈', 'description' => 'Focus on making microscopic daily gains rather than attempting massive overnight transformations.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 6],
            ['name' => 'Two-Minute Rule', 'category' => 'Discipline', 'icon' => '⚡', 'description' => 'Downscale a new habit so it takes less than two minutes to complete, making it easy to start.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 7],
            ['name' => 'Visual Habit Tracking', 'category' => 'Discipline', 'icon' => '📅', 'description' => 'Mark an X on a physical calendar every time you complete your habit to maintain a visual streak.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 8],
            ['name' => 'Never Miss Twice', 'category' => 'Discipline', 'icon' => '↩️', 'description' => 'If you miss a habit one day, commit to getting back on track the very next day without judgment.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 9],
            ['name' => 'Pre-commitment Devices', 'category' => 'Discipline', 'icon' => '🔒', 'description' => 'Restrict your future choices to prevent bad habits, like leaving credit cards at home when going out.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 10],
            ['name' => 'Setting Process Goals', 'category' => 'Discipline', 'icon' => '⚙️', 'description' => 'Focus your discipline on the system of doing the work rather than the final outcome.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 11],
            ['name' => 'Keeping a To-Don\'t List', 'category' => 'Discipline', 'icon' => '🚫', 'description' => 'Explicitly list actions you commit to never doing during your productive hours.', 'goal' => 4, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 12],
            ['name' => 'Habit Contracts', 'category' => 'Discipline', 'icon' => '🤝', 'description' => 'Sign a verbal or written agreement with an accountability partner outlining a punishment if you fail a habit.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 13],
            ['name' => 'Positive Procrastination', 'category' => 'Discipline', 'icon' => '⏳', 'description' => 'Tell yourself "I\'ll do it later" when facing a temptation, allowing your rational mind time to regain control.', 'goal' => 21, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 14],
            ['name' => 'Stepwise Habit Replacement', 'category' => 'Discipline', 'icon' => '🔀', 'description' => 'Gradually step-down a bad habit over months, substituting it with progressively healthier alternatives.', 'goal' => 90, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 3, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 15],

            // ─── LEARNING ───
            ['name' => 'Deliberate Practice', 'category' => 'Learning', 'icon' => '🎯', 'description' => 'Engage in focused, effortful practice targeting specific weaknesses with full concentration.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 1],
            ['name' => 'Seeking Immediate Feedback', 'category' => 'Learning', 'icon' => '💬', 'description' => 'Ask a coach or use tools to get real-time feedback on your practice errors to correct them instantly.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 2],
            ['name' => 'Reading Good Books', 'category' => 'Learning', 'icon' => '📚', 'description' => 'Dedicate time daily to reading non-fiction or classics for mental renewal and knowledge acquisition.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 3],
            ['name' => 'Active Recall Practice', 'category' => 'Learning', 'icon' => '🧠', 'description' => 'Study by retrieving information from memory rather than passively rereading your notes.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 4],
            ['name' => 'Building a Second Brain', 'category' => 'Learning', 'icon' => '🗂️', 'description' => 'Capture, organize, distill, and express digital notes to reduce cognitive load and enhance creativity.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 5],
            ['name' => 'Feynman Technique', 'category' => 'Learning', 'icon' => '💡', 'description' => 'Teach a complex concept in simple terms to identify gaps in your understanding.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 6],
            ['name' => '5-Hour Rule', 'category' => 'Learning', 'icon' => '⏰', 'description' => 'Dedicate at least five hours a week specifically to deliberate learning and reading.', 'goal' => 12, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 3, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 7],
            ['name' => 'Reproducing Expert Work', 'category' => 'Learning', 'icon' => '🎨', 'description' => 'Study expert work, put it away, try to recreate it from memory, and compare it to the original.', 'goal' => 12, 'goal_unit' => 'weeks', 'repeat_count' => 2, 'deadline_value' => 3, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 8],
            ['name' => 'Pre-testing Knowledge', 'category' => 'Learning', 'icon' => '✅', 'description' => 'Test yourself on material before studying it to prime the brain for acquiring new information.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 9],
            ['name' => 'Breaking Skills into Micro-components', 'category' => 'Learning', 'icon' => '🔬', 'description' => 'Focus your practice on one tiny sub-skill at a time until it is fully mastered.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 10],
            ['name' => 'Systematic A/B Testing', 'category' => 'Learning', 'icon' => '🔀', 'description' => 'Systematically alter your approach to a task to gather data on what yields the best performance.', 'goal' => 8, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 2, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 11],
            ['name' => 'Goal Pyramid Alignment', 'category' => 'Learning', 'icon' => '🔺', 'description' => 'Connect low-level daily learning tasks to a single top-level ultimate goal to maintain coherence.', 'goal' => 12, 'goal_unit' => 'months', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 1, 'sort_order' => 12],
            ['name' => 'Automating Measurement', 'category' => 'Learning', 'icon' => '📱', 'description' => 'Use digital trackers to log your progress immediately after a learning session is completed.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 13],

            // ─── SOCIAL SKILLS ───
            ['name' => 'Active-Constructive Responding', 'category' => 'Social Skills', 'icon' => '🎉', 'description' => 'Respond enthusiastically and ask engaging questions when someone shares good news with you.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 1],
            ['name' => 'Scheduling Date Days', 'category' => 'Social Skills', 'icon' => '💑', 'description' => 'Put dedicated time with your significant other on your calendar to ensure they get your best energy.', 'goal' => 8, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 2, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 2],
            ['name' => 'Scheduling Friend Get-Togethers', 'category' => 'Social Skills', 'icon' => '👥', 'description' => 'Block out regular time on your calendar specifically for maintaining and nurturing friendships.', 'goal' => 8, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 2, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 3],
            ['name' => 'Expressing Gratitude to Others', 'category' => 'Social Skills', 'icon' => '🙏', 'description' => 'Explicitly tell people what you appreciate about them and what they mean to your life.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 4],
            ['name' => 'Seeking an Accountability Partner', 'category' => 'Social Skills', 'icon' => '🤜', 'description' => 'Ask someone to watch your behavior and hold you to your commitments to create a social cost for failure.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 5],
            ['name' => 'Empathetic Listening', 'category' => 'Social Skills', 'icon' => '👂', 'description' => 'Seek first to understand the other person deeply before trying to be understood yourself.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 6],
            ['name' => 'Nonviolent Communication', 'category' => 'Social Skills', 'icon' => '🕊️', 'description' => 'Express your needs clearly without blame to enhance empathetic communication.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 7],
            ['name' => 'Mentoring Others', 'category' => 'Social Skills', 'icon' => '🎓', 'description' => 'Teach your skills to others to reinforce your own identity and mastery.', 'goal' => 12, 'goal_unit' => 'months', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 2, 'sort_order' => 8],
            ['name' => 'Volunteering', 'category' => 'Social Skills', 'icon' => '❤️', 'description' => 'Contribute to your community through volunteering to build a sense of purpose and spiritual renewal.', 'goal' => 12, 'goal_unit' => 'months', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 2, 'sort_order' => 9],
            ['name' => 'Joining a Supportive Culture', 'category' => 'Social Skills', 'icon' => '🏘️', 'description' => 'Surround yourself with a tribe where your desired behavior is the normal behavior.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 10],
            ['name' => 'Empathy Mapping', 'category' => 'Social Skills', 'icon' => '🗺️', 'description' => 'Consciously map out what others are thinking and feeling to improve communication and understanding.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 11],
            ['name' => 'Finding a Training Partner', 'category' => 'Social Skills', 'icon' => '🤸', 'description' => 'Pair up with someone learning the same skill for mutual support, feedback, and motivation.', 'goal' => 8, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 2, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 12],

            // ─── FINANCIAL HABITS ───
            ['name' => 'Automating Savings Plans', 'category' => 'Financial Habits', 'icon' => '🏦', 'description' => 'Set up automatic transfers to investment or savings accounts so the decision is made before you can spend.', 'goal' => 12, 'goal_unit' => 'months', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 1, 'sort_order' => 1],
            ['name' => 'Tracking Spending', 'category' => 'Financial Habits', 'icon' => '💳', 'description' => 'Monitor your daily expenses just as you would monitor fitness goals to build profound self-awareness.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 2],
            ['name' => 'Packing Lunches', 'category' => 'Financial Habits', 'icon' => '🥪', 'description' => 'Consistently bring your lunch from home instead of eating out to compound financial savings over time.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 3],
            ['name' => 'Delaying Gratification', 'category' => 'Financial Habits', 'icon' => '⏳', 'description' => 'Tell yourself "I\'ll buy it later" to let the rational mind regain control over impulse purchases.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 4],
            ['name' => 'Reviewing Life Domains for Abundance', 'category' => 'Financial Habits', 'icon' => '🌟', 'description' => 'Appreciate non-financial values to avoid the trap of needing extreme wealth to be happy.', 'goal' => 4, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 5],
            ['name' => 'Investing 1% Better Every Day', 'category' => 'Financial Habits', 'icon' => '📊', 'description' => 'Focus on compounding small financial improvements over time rather than chasing massive, risky shifts.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 6],
            ['name' => 'Aligning Spending with Values', 'category' => 'Financial Habits', 'icon' => '💎', 'description' => 'Check your expenses against your core values to ensure your money supports your ideal identity.', 'goal' => 12, 'goal_unit' => 'months', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 1, 'sort_order' => 7],
            ['name' => 'Reviewing Cost of Bad Habits', 'category' => 'Financial Habits', 'icon' => '🔍', 'description' => 'Calculate the exact financial cost of your bad habits to make them intellectually unattractive.', 'goal' => 12, 'goal_unit' => 'months', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 2, 'sort_order' => 8],
            ['name' => 'Establishing Spending Rules', 'category' => 'Financial Habits', 'icon' => '📏', 'description' => 'Create rules like "If I want a luxury item, I will wait 48 hours first" to curb impulses.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 9],
            ['name' => 'Valuing Time Over Money', 'category' => 'Financial Habits', 'icon' => '⌚', 'description' => 'Guard your time tightly, recognizing it as your most precious and finite asset.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 10],
            ['name' => 'Saving for Visual Rewards', 'category' => 'Financial Habits', 'icon' => '🎯', 'description' => 'Open a dedicated savings account for a specific item to make the act of saving satisfying.', 'goal' => 12, 'goal_unit' => 'months', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 2, 'sort_order' => 11],
            ['name' => 'Creating a Financial Habit Contract', 'category' => 'Financial Habits', 'icon' => '📜', 'description' => 'Agree to pay a financial penalty to a friend if you fail to meet a savings or behavioral goal.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 12],

            // ─── CAREER GROWTH ───
            ['name' => 'Time-Blocking Deep Work', 'category' => 'Career Growth', 'icon' => '🔵', 'description' => 'Block out distraction-free time on your calendar specifically for high-value, cognitively demanding tasks.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 1],
            ['name' => 'Setting Aside Learning Time', 'category' => 'Career Growth', 'icon' => '📖', 'description' => 'Treat continuous learning and skill development as a non-negotiable career appointment.', 'goal' => 12, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 3, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 2],
            ['name' => 'Annual Review', 'category' => 'Career Growth', 'icon' => '🗓️', 'description' => 'Every December, tally your habits and answer: What went well? What didn\'t? What did I learn?', 'goal' => 1, 'goal_unit' => 'years', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 1, 'sort_order' => 3],
            ['name' => 'Shutdown Ritual', 'category' => 'Career Growth', 'icon' => '🌙', 'description' => 'Write down your top 3 tasks for tomorrow at the end of the workday to close open mental loops.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 4],
            ['name' => 'Focusing on Lead Measures', 'category' => 'Career Growth', 'icon' => '📏', 'description' => 'Focus your efforts on controllable daily inputs rather than lagging outcome measures.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 5],
            ['name' => 'Eliminating Non-Essential Opportunities', 'category' => 'Career Growth', 'icon' => '✂️', 'description' => 'Gracefully say no to middling career opportunities to avoid over-commitment.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 6],
            ['name' => 'Job Crafting', 'category' => 'Career Growth', 'icon' => '🔨', 'description' => 'Make small, meaningful changes to your current job duties to enhance their connection to your core values.', 'goal' => 12, 'goal_unit' => 'months', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 2, 'sort_order' => 7],
            ['name' => 'Taking Personal Retreat Days', 'category' => 'Career Growth', 'icon' => '🏔️', 'description' => 'Take a full day away from the office for high-level strategic planning and reflection.', 'goal' => 4, 'goal_unit' => 'months', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 2, 'sort_order' => 8],
            ['name' => 'Proactive Problem Solving', 'category' => 'Career Growth', 'icon' => '💡', 'description' => 'Take the initiative to improve a work situation rather than waiting to be told what to do.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 9],
            ['name' => 'Beginning with the End in Mind', 'category' => 'Career Growth', 'icon' => '🎯', 'description' => 'Envision your ultimate career outcome before embarking on a new project or role.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 10],
            ['name' => 'Mastering the Decisive Moment', 'category' => 'Career Growth', 'icon' => '⚡', 'description' => 'Optimize the small choices that dictate your whole workday.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 11],
            ['name' => 'Integrity Report', 'category' => 'Career Growth', 'icon' => '📋', 'description' => 'Every six months, revisit your core values and assess if your work aligns with them.', 'goal' => 2, 'goal_unit' => 'years', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 1, 'sort_order' => 12],
            ['name' => 'Time Auditing', 'category' => 'Career Growth', 'icon' => '🕐', 'description' => 'Track exactly how you spend your 168 hours a week to reclaim lost productivity and reallocate time.', 'goal' => 1, 'goal_unit' => 'years', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 2, 'sort_order' => 13],

            // ─── EMOTIONAL INTELLIGENCE ───
            ['name' => 'Practicing Self-Compassion', 'category' => 'Emotional Intelligence', 'icon' => '💙', 'description' => 'Talk to yourself like a friend when you experience a setback, rather than using harsh self-criticism.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 1],
            ['name' => 'Daily Gratitude Journaling', 'category' => 'Emotional Intelligence', 'icon' => '🙏', 'description' => 'Write down three things you are grateful for to train the brain to scan for positives rather than threats.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 2],
            ['name' => 'Unplugged Silence', 'category' => 'Emotional Intelligence', 'icon' => '🤫', 'description' => 'Sit in silence without music or devices to rejuvenate the mind and spark new ideas.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 3],
            ['name' => 'Reframing "I have to"', 'category' => 'Emotional Intelligence', 'icon' => '🔄', 'description' => 'Change your language to "I get to" to make hard tasks psychologically attractive.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 4],
            ['name' => 'Embracing Radical Incrementalism', 'category' => 'Emotional Intelligence', 'icon' => '🐢', 'description' => 'Stop working when your scheduled time is up to train your subconscious to be patient and avoid burnout.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 5],
            ['name' => 'Enjoying Missing Out (JOMO)', 'category' => 'Emotional Intelligence', 'icon' => '😌', 'description' => 'Practice the joy of missing out by intentionally skipping trivial events to focus on what matters.', 'goal' => 4, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 6],
            ['name' => 'Accepting Inner Conflict', 'category' => 'Emotional Intelligence', 'icon' => '⚖️', 'description' => 'Recognize that conflicting desires are completely normal human experiences.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 7],
            ['name' => 'Practicing Productive Meditation', 'category' => 'Emotional Intelligence', 'icon' => '🚶', 'description' => 'Focus on a single professional problem while walking or commuting, gently returning attention when it wanders.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 8],
            ['name' => 'Letting Go of Perfection', 'category' => 'Emotional Intelligence', 'icon' => '🌸', 'description' => 'Accept that making mistakes is a fundamental part of learning and being human.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 9],
            ['name' => 'Checking in with Values', 'category' => 'Emotional Intelligence', 'icon' => '🧭', 'description' => 'Ask yourself "How true have I been to my values this week?" at the end of every week.', 'goal' => 12, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 3, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 10],
            ['name' => 'Separating Action from Emotion', 'category' => 'Emotional Intelligence', 'icon' => '🎭', 'description' => 'Practice doing the right thing even when your emotional state is completely negative.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 11],
            ['name' => 'Avoiding the "What the Hell" Effect', 'category' => 'Emotional Intelligence', 'icon' => '🛡️', 'description' => 'Treat small lapses as temporary mistakes rather than reasons to completely abandon your goals.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 12],
            ['name' => 'Mindful Frustration Tolerance', 'category' => 'Emotional Intelligence', 'icon' => '😤', 'description' => 'Use frustrating situations as opportunities to practice patience and focus.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 13],
            ['name' => 'Recognizing Reasons as Excuses', 'category' => 'Emotional Intelligence', 'icon' => '🔎', 'description' => 'Acknowledge that thoughts like "I\'m too tired" are often just excuses generated by the mind, not absolute facts.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 14],

            // ─── CREATIVITY ───
            ['name' => 'Taking Nature Walks for Creativity', 'category' => 'Creativity', 'icon' => '🌿', 'description' => 'Spend time in nature to hasten the transition to a restful state and promote subconscious problem-solving.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 1],
            ['name' => 'Harnessing Incubation Periods', 'category' => 'Creativity', 'icon' => '🌱', 'description' => 'Schedule time for mind-wandering activities like showering or walking to synthesize new ideas.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 2],
            ['name' => 'Designing an Activity Zone', 'category' => 'Creativity', 'icon' => '🎨', 'description' => 'Create dedicated physical spaces for writing, reading, or painting to trigger creative habits contextually.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 3],
            ['name' => 'Standardizing Before Optimizing', 'category' => 'Creativity', 'icon' => '📐', 'description' => 'Master the habit of simply showing up to your creative workspace before worrying about the quality of the work.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 4],
            ['name' => 'Cultivating Autotelic Experiences', 'category' => 'Creativity', 'icon' => '🎮', 'description' => 'Turn mundane tasks into engaging games by setting micro-goals to intrinsically motivate the brain.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 5],
            ['name' => 'Capturing Ideas Immediately', 'category' => 'Creativity', 'icon' => '💡', 'description' => 'Write down creative ideas the moment they occur to prevent mental clutter and anxiety.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 6],
            ['name' => 'Engaging in Deep Work', 'category' => 'Creativity', 'icon' => '🔮', 'description' => 'Eliminate all distractions and focus entirely on a cognitively demanding creative task for maximum output.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 7],
            ['name' => 'Reviewing Masterworks', 'category' => 'Creativity', 'icon' => '🖼️', 'description' => 'Deconstruct the work of top performers in your field to build better mental representations of success.', 'goal' => 8, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 2, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 8],
            ['name' => 'Maintaining a Beginner\'s Mind', 'category' => 'Creativity', 'icon' => '👶', 'description' => 'Study familiar objects or processes as if you are seeing them for the very first time to spark new ideas.', 'goal' => 4, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 3, 'sort_order' => 9],
            ['name' => 'Visualizing the Process', 'category' => 'Creativity', 'icon' => '🎬', 'description' => 'Mentally walk through every step of a creative project before actually starting the physical work.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 10],
            ['name' => 'Valuing the Chase', 'category' => 'Creativity', 'icon' => '🏃', 'description' => 'Focus on falling in love with the process of creating rather than fixating on the final product.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 11],

            // ─── DIGITAL HYGIENE ───
            ['name' => 'Uninstalling Unused Phone Apps', 'category' => 'Digital Hygiene', 'icon' => '🗑️', 'description' => 'Delete apps that you no longer need to remove visual triggers from your phone.', 'goal' => 12, 'goal_unit' => 'months', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'years', 'priority' => 2, 'sort_order' => 1],
            ['name' => 'Moving Social Media to Desktop', 'category' => 'Digital Hygiene', 'icon' => '💻', 'description' => 'Delete social apps from your phone and only access them via your computer at scheduled times.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 2],
            ['name' => 'Changing Notification Settings', 'category' => 'Digital Hygiene', 'icon' => '🔕', 'description' => 'Turn off all visual and auditory push notifications except for essential calls and texts.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 3],
            ['name' => 'Wearing a Wristwatch', 'category' => 'Digital Hygiene', 'icon' => '⌚', 'description' => 'Check the time on a watch instead of your phone to avoid getting sucked into checking notifications.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 4],
            ['name' => 'Turning Off Desktop Notifications', 'category' => 'Digital Hygiene', 'icon' => '🖥️', 'description' => 'Disable all alerts and pop-ups on your computer to ensure uninterrupted focused work.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 5],
            ['name' => 'Clearing the Desktop', 'category' => 'Digital Hygiene', 'icon' => '🧹', 'description' => 'Move all files to an "Everything" folder to reduce digital visual clutter and distraction.', 'goal' => 4, 'goal_unit' => 'weeks', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 3, 'sort_order' => 6],
            ['name' => 'Saving Articles to Read Later', 'category' => 'Digital Hygiene', 'icon' => '📌', 'description' => 'Save interesting online articles to an app to read them later at a scheduled time rather than immediately.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 7],
            ['name' => 'Using News Feed Eradicators', 'category' => 'Digital Hygiene', 'icon' => '🚧', 'description' => 'Install browser extensions that block endless scrolling feeds on social media platforms.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 8],
            ['name' => 'Using Website Blockers', 'category' => 'Digital Hygiene', 'icon' => '🔒', 'description' => 'Use apps to physically block distracting websites during your designated work hours.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 9],
            ['name' => 'Rearranging Home Screen', 'category' => 'Digital Hygiene', 'icon' => '📱', 'description' => 'Move distracting apps to the last screen of your phone or hide them in folders.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 10],

            // ─── SLEEP & RECOVERY ───
            ['name' => '7-9 Hours of Sleep', 'category' => 'Sleep & Recovery', 'icon' => '😴', 'description' => 'Prioritize getting enough sleep to allow your brain to consolidate learning and recover willpower.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 1],
            ['name' => 'Digital Sabbatical Before Bed', 'category' => 'Sleep & Recovery', 'icon' => '📵', 'description' => 'Turn off all screens 60 minutes before sleep to restore melatonin production and protect the asset.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 2],
            ['name' => 'Leaving Phone Outside Bedroom', 'category' => 'Sleep & Recovery', 'icon' => '🚪', 'description' => 'Charge your smartphone in another room to prevent late-night or early-morning mindless scrolling.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 1, 'sort_order' => 3],
            ['name' => 'Automatically Turning Off Internet', 'category' => 'Sleep & Recovery', 'icon' => '📡', 'description' => 'Set your home router to disable internet access at a specific time each evening to force offline recovery.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 2, 'sort_order' => 4],
            ['name' => 'Napping Under 30 Minutes', 'category' => 'Sleep & Recovery', 'icon' => '💤', 'description' => 'Take short naps to restore energy without entering deep sleep and waking up with groggy sleep inertia.', 'goal' => 30, 'goal_unit' => 'days', 'repeat_count' => 1, 'deadline_value' => 1, 'deadline_unit' => 'months', 'priority' => 3, 'sort_order' => 5],
        ];

        // Add timestamps to all records
        $records = array_map(function ($template) use ($now) {
            return array_merge($template, [
            'created_at' => $now,
            'updated_at' => $now,
            ]);
        }, $templates);

        // Insert in chunks to avoid memory issues
        foreach (array_chunk($records, 50) as $chunk) {
            DB::table('habit_templates')->insert($chunk);
        }

        $count = DB::table('habit_templates')->count();
        $this->command->info("✅ Seeded {$count} habit templates successfully!");
    }
}