<?php

return [

    'free' => [
        'name'                => 'Free',
        'habits_limit'        => 5,
        'ai_messages_per_day' => 3,
        'ai_model'            => 'groq',
        'analytics_days'      => 7,
        'job_apps_limit'      => 3,
        'templates_limit'     => 25,
        'friends'             => false,
        'mood'                => true,
        'mood_correlation'    => false,
        'diary'               => false,
        'pomodoro'            => true,
        'cv_upload'           => false,
        'export'              => false,
        'chrome_extension'    => true,
        'weekly_ai_summary'   => false,
        'notifications'       => true,
        'job_tracker'         => false,
        'ats_scoring'         => false,
        'cover_letter'        => false,
        'company_research'    => false,
    ],

    'pro' => [
        'name'                => 'Pro',
        'habits_limit'        => 15,
        'ai_messages_per_day' => 15,
        'ai_model'            => 'claude-haiku',
        'analytics_days'      => 30,
        'job_apps_limit'      => 20,
        'templates_limit'     => -1,
        'friends'             => true,
        'mood'                => true,
        'mood_correlation'    => true,
        'diary'               => true,
        'pomodoro'            => true,
        'cv_upload'           => false,
        'export'              => true,
        'chrome_extension'    => true,
        'weekly_ai_summary'   => true,
        'notifications'       => true,
        'job_tracker'         => true,
        'ats_scoring'         => false,
        'cover_letter'        => true,
        'company_research'    => true,
    ],

    'max' => [
        'name'                => 'Max',
        'habits_limit'        => -1,
        'ai_messages_per_day' => -1,
        'ai_model'            => 'claude-sonnet',
        'analytics_days'      => -1,
        'job_apps_limit'      => -1,
        'templates_limit'     => -1,
        'friends'             => true,
        'mood'                => true,
        'mood_correlation'    => true,
        'diary'               => true,
        'pomodoro'            => true,
        'cv_upload'           => true,
        'export'              => true,
        'chrome_extension'    => true,
        'weekly_ai_summary'   => true,
        'notifications'       => true,
        'job_tracker'         => true,
        'ats_scoring'         => true,
        'cover_letter'        => true,
        'company_research'    => true,
    ],

];
